// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsybxembykxiykgkdlth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzeWJ4ZW1ieWt4aXlrZ2tkbHRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MTIwNzMsImV4cCI6MjA3NjE4ODA3M30.pJgWDdZwhCWiwVA31DF9uVbFrMAN53Cm0Z_7i5msqA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});